name: C/C++ CI

on:
  push:
    branches: [ master, HomeworkBowling ]
  pull_request:
    branches: [ master, HomeworkBowling ]

jobs:
  BowlingGame:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: mkdir shm/build
      run: mkdir shm/build
    - name: Compile
      working-directory: shm/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: shm/build
      run: ctest -V   
