name: C/C++ CI

on: [push, pull_request]

jobs:
  BowlingGame:

    runs-on: [ubuntu-20.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: mkdir bowling/build
      run: mkdir bowling/build
    - name: Compile
      working-directory: bowling/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: bowling/build
      run: ctest -V   
